---
- name: Create installation directory
  file:
    path: '{{ grafana_path }}'
    state: directory
    owner: '{{ grafana_user }}'
    group: '{{ grafana_group }}'
    mode: 0775
- name: Get grafana user info
  ansible.builtin.getent:
    database: passwd
    key: '{{ grafana_user }}'
- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: 'docker-compose.yml.j2'
    dest: '{{ grafana_path }}/docker-compose.yml'
    owner: '{{ grafana_user }}'
    group: '{{ grafana_group }}'
    mode: 0664
  vars:
    grafana_user_id: '{{ ansible_facts.getent_passwd[grafana_user][1] }}'
    grafana_group_id: '{{ ansible_facts.getent_passwd[grafana_group][1] }}'
- name: Enable daily upgrade of base image
  ansible.builtin.cron:
    name: 'Upgrade {{ grafana_path }}'
    user: root
    hour: 4
    minute: 0
    job: 'docker compose -f {{ grafana_path }}/docker-compose.yml down && docker compose -f {{ grafana_path }}/docker-compose.yml pull && docker compose -f {{ grafana_path }}/docker-compose.yml up -d'
- name: Copy backup_grafana.sh
  ansible.builtin.template:
    src: backup_grafana.sh.j2
    dest: '{{ grafana_path }}/backup_grafana.sh'
    owner: root
    group: root
    mode: 0775
- name: Enable daily backup
  ansible.builtin.cron:
    name: 'Backup {{ grafana_path }}'
    user: root
    hour: 1
    minute: 0
    job: '{{ grafana_path }}/backup_grafana.sh'
